name: GitHub Metrics

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - name: Generate isometric contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-isocalendar.svg
          token: ${{ github.token }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Shanghai
