name: GitHub Metrics

on:
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  skyline:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: github-skyline.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2026
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.7
